# Generated by Django 5.0 on 2024-05-23 15:37

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('episode', '0002_alter_episode_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='episode',
            name='music',
            field=models.FileField(blank=True, null=True, upload_to='episodes/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3'])]),
        ),
        migrations.AlterField(
            model_name='episode',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='episode.tag'),
        ),
    ]
